name: Sync pages from obsidian

on: 
  schedule :
    - cron: '0 0 * * *' # Une fois par jour, à minuit
  workflow_dispatch:

jobs: 
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Hugo site
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: hugo-site

    - name: Checkout Obsidian vault
      uses: actions/checkout@v4
      with: 
        repository: geoffreyv/obsidian-vault
        ssh-key: ${{ secrets.SSH_OBSIDIAN }}
        path: obsidian-vault

    - name: Copier contenu du cours vers le contenu Hugo
      run: |
        rm -rf hugo-site/content/cours
        mkdir -p hugo-site/content/cours
        cp -r obsidian-vault/cours/* hugo-site/content/cours

    - name: Convertir liens Obsidian + copier images
      run: |
        python3 hugo-site/scripts/convert-obsidian.py
        python3 hugo-site/scripts/convert-boxes.py
        
    - name: Commit et push
      uses: EndBug/add-and-commit@v9
      with:
        message: "Sync Obsidian vers Hugo"
        add: 'content/cours'
        cwd: hugo-site
        default_author: github_actor
