name: 01 - Sync pages from obsidian

on: 
  schedule :
    - cron: '0 0 * * *' # Une fois par jour, à minuit
  workflow_dispatch:
  push:

jobs: 
  sync:
    runs-on: ubuntu-latest
    outputs:
      new-ref: ${{ steps.set-sha.outputs.sha }}

    steps:
    - name: Checkout Hugo site
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: hugo-site

    - name: Checkout Obsidian vault
      uses: actions/checkout@v4
      with: 
        repository: IUT-GEII-Annecy/Supports
        ssh-key: ${{ secrets.SSH_OBSIDIAN }}
        path: obsidian-vault

    - name: Copier contenu du cours vers le contenu Hugo
      run: |
        rm -rf hugo-site/content/docs
        mkdir -p hugo-site/content/docs
        cp -r obsidian-vault/cours/* hugo-site/content/docs
        rm -rf hugo-site/static/images
        mkdir -p hugo-site/static/images

    - name: Convertir liens Obsidian + copier images
      run: |
        python3 hugo-site/scripts/convert-obsidian.py
        
    - name: Commit et push
      id: commit
      uses: EndBug/add-and-commit@v9
      with:
        message: "Sync Obsidian vers Hugo"
        add: |
          'content/**'
          'static/images'
        cwd: hugo-site
        default_author: github_actor

    - name: Get pushed commit sha
      id: set-sha
      run: |
        cd hugo-site
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  deploy:
    needs: sync
    uses: ./.github/workflows/static.yml
    with:
      ref: ${{ needs.sync.outputs.new-ref }}


